#!/usr/bin/env python3
"""Regenerate frontend/sandbox_preview/vendor/three.datauri.js from a Three.js ES module build.

The Run-mode preview gives pages ``import * as THREE from 'three'`` through an import map whose target is a data:
URL, so the sandboxed frame needs no network and no same-origin fetch. The component cannot read its own vendored
file (its policy has no connect-src), so the module is shipped as a script that assigns the data URL to a global.

Usage: python scripts/build_three_datauri.py path/to/three.module.min.js [version]
Source: the ``build/three.module.min.js`` file of the three npm package (MIT; LICENSE kept beside the output).
"""
from __future__ import annotations

import base64
import pathlib
import sys

OUT = pathlib.Path(__file__).resolve().parent.parent / "frontend" / "sandbox_preview" / "vendor" / "three.datauri.js"


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        print(__doc__)
        return 2
    source = pathlib.Path(argv[1]).read_bytes()
    version = argv[2] if len(argv) > 2 else "unknown"
    data_url = "data:text/javascript;base64," + base64.b64encode(source).decode("ascii")
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(
        f"// Three.js {version} ES module build as a data: URL (MIT, see THREE_LICENSE). Generated by scripts/build_three_datauri.py; do not edit.\n"
        f'window.__THREE_MODULE_DATA_URL = "{data_url}";\nwindow.__THREE_VERSION = "{version}";\n'
    )
    print(f"wrote {OUT} ({OUT.stat().st_size} bytes) from {len(source)} source bytes")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
